On Python 3.6 and lower:
Python library multiprocessing can't deal with very large data transfer for parallel computing, causing error "struct.error: 'i' format requires -2147483648 <= number <= 2147483647".

